services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
    container_name: next_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    command: npm run dev
    depends_on:
      - backend