FROM python:3.10.14

WORKDIR /backend


ENV PYTHONPATH=/backend

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]